defaults:
  - base
  - _self_

seed: 1111

preferred_spawn_biome: "plains"
candidate_preferred_spawn_biome: 
  - plains
  - desert

task_conf:
  - name: "kill_entity"
    text: "kill_entity:sheep" 


reward_conf:
  - event: "pickup"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "mutton"
    identity: "kill entities"

mobs: 
  - name: "sheep"
    number: 30
    range_x:  [-20, 20]
    range_z:  [-20, 20]

init_inventory:
  - slot: 0
    type: "iron_sword"
    quantity: 1

