defaults:
  - base
  - _self_



task_conf:
  - name: "cooked_beef"
    text: "cooked_beef" 

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "cooked_beef"
    identity: "cooked_beef"
  
init_inventory: 
  - slot: 0
    type: furnace
    quantity: 1
  - slot: 20
    type: coal
    quantity: 10
  - slot: 14
    type: beef
    quantity: 10

need_furnace: True
need_gui: True

worker:
  "smelt"