defaults:
  - base
  - _self_

task_conf:
  - name: "craft"
    text: "craft item diamond_sword" 

reward_conf:
  - event: "craft_item"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "diamond_sword"
    identity: "craft diamond_sword"
  
init_inventory: 
  - slot: 0
    type: crafting_table
    quantity: 1
  - slot: 10
    type: diamond
    quantity: ">=2"
  - slot: 14
    type: stick
    quantity: ">=7"

need_gui: True
need_crafting_table: True
