defaults:
  - base
  - _self_

candidate_preferred_spawn_biome: 
  - "forest"

task_conf:
  - name: "mine"
    text: "mine_block:oak_leaves" 

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects: 
      - "oak_leaves"
    identity: "mine oak_leaves"
  
init_inventory: 
  - slot: 0
    type: "wooden_axe"
    quantity: 1